AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SkillId:
    Type: String
  LambdaRuntime:
    Type: String
  LambdaHandler:
    Type: String
  CodeBucket:
    Type: String
  CodeKey:
    Type: String
  CodeVersion:
    Type: String
Resources:
  AlexaSkillIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: alexaSkillExecutionPolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:*
                  Resource: arn:aws:logs:*:*:*
          - PolicyName: alexaSkillDynamodbPolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:*
                    - dax:*
                    - application-autoscaling:DeleteScalingPolicy
                    - application-autoscaling:DeregisterScalableTarget
                    - application-autoscaling:DescribeScalableTargets
                    - application-autoscaling:DescribeScalingActivities
                    - application-autoscaling:DescribeScalingPolicies
                    - application-autoscaling:PutScalingPolicy
                    - application-autoscaling:RegisterScalableTarget
                    - cloudwatch:DeleteAlarms
                    - cloudwatch:DescribeAlarmHistory
                    - cloudwatch:DescribeAlarms
                    - cloudwatch:DescribeAlarmsForMetric
                    - cloudwatch:GetMetricStatistics
                    - cloudwatch:ListMetrics
                    - cloudwatch:PutMetricAlarm
                    - cloudwatch:GetMetricData
                    - datapipeline:ActivatePipeline
                    - datapipeline:CreatePipeline
                    - datapipeline:DeletePipeline
                    - datapipeline:DescribeObjects
                    - datapipeline:DescribePipelines
                    - datapipeline:GetPipelineDefinition
                    - datapipeline:ListPipelines
                    - datapipeline:PutPipelineDefinition
                    - datapipeline:QueryObjects
                    - ec2:DescribeVpcs
                    - ec2:DescribeSubnets
                    - ec2:DescribeSecurityGroups
                    - iam:GetRole
                    - iam:ListRoles
                    - kms:DescribeKey
                    - kms:ListAliases
                    - sns:CreateTopic
                    - sns:DeleteTopic
                    - sns:ListSubscriptions
                    - sns:ListSubscriptionsByTopic
                    - sns:ListTopics
                    - sns:Subscribe
                    - sns:Unsubscribe
                    - sns:SetTopicAttributes
                    - lambda:CreateFunction
                    - lambda:ListFunctions
                    - lambda:ListEventSourceMappings
                    - lambda:CreateEventSourceMapping
                    - lambda:DeleteEventSourceMapping
                    - lambda:GetFunctionConfiguration
                    - lambda:DeleteFunction
                    - resource-groups:ListGroups
                    - resource-groups:ListGroupResources
                    - resource-groups:GetGroup
                    - resource-groups:GetGroupQuery
                    - resource-groups:DeleteGroup
                    - resource-groups:CreateGroup
                    - tag:GetResources
                    - kinesis:ListStreams
                    - kinesis:DescribeStream
                    - kinesis:DescribeStreamSummary
                  Resource: "*"
  AlexaSkillFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
        S3ObjectVersion: !Ref CodeVersion
      Handler: !Ref LambdaHandler
      Runtime: !Ref LambdaRuntime
      Role: !GetAtt AlexaSkillIAMRole.Arn
      MemorySize: 512
      Timeout: 60
  AlexaSkillFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt AlexaSkillFunction.Arn
      Principal: alexa-appkit.amazon.com
      EventSourceToken: !Ref SkillId
  AlexaSkillFunctionEventPermissionSmartHome:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt AlexaSkillFunction.Arn
      Principal: alexa-connectedhome.amazon.com
      EventSourceToken: !Ref SkillId
  AlexaSkillFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlexaSkillFunction}
      RetentionInDays: 14
Outputs:
  SkillEndpoint:
    Description: LambdaARN for the regional endpoint
    Value: !GetAtt AlexaSkillFunction.Arn
